/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ttmp;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author devga
 */
public class ClassandRoomManager extends javax.swing.JFrame {
    char currentType = 'c';
    char mode = 'c';
    private I_Class currentClass;
    private Room currentRoom;
    javax.swing.JFrame parentClass;
    /**
     * Creates new form ClassandRoomManager
     */
    public ClassandRoomManager() {
        initComponents();
        applyMode();
        applyType();
    }
    public ClassandRoomManager(I_Class clas) {
        mode = 'e';
        currentType = 'c';
        currentClass = clas;
        initComponents();
        applyMode();
        applyType();
    }
    public ClassandRoomManager(I_Class clas, javax.swing.JFrame parentClass) {
        mode = 'e';
        currentType = 'c';
        currentClass = clas;
        this.parentClass = parentClass;
        initComponents();
        applyMode();
        applyType();
    }
    public ClassandRoomManager(Room room) {
        initComponents();
        mode = 'e';
        currentType = 'r';
        currentRoom = room;
        applyMode();
        applyType();
    }
    public ClassandRoomManager(Room room, javax.swing.JFrame parentClass) {
        initComponents();
        mode = 'e';
        currentType = 'r';
        currentRoom = room;
        this.parentClass = parentClass;
        applyMode();
        applyType();
    }
    private void applyMode()
    {
        switch(mode)
        {
            case 'c':
                jAddButton.setEnabled(true);
                j_RAddButton.setEnabled(true);
                j_RNoField.setEditable(true);
                jRemoveButton.setEnabled(false);
                j_RRemoveButton.setEnabled(false);
                jUpdateButton.setEnabled(false);
                j_RUpdateButton.setEnabled(false);
                jTypeSelectorBox.removeAllItems();
                jTypeSelectorBox.addItem("Class");
                jTypeSelectorBox.addItem("Room");
                break;
            case 'e':
                jAddButton.setEnabled(false);
                j_RAddButton.setEnabled(false);
                jRemoveButton.setEnabled(true);
                j_RNoField.setEditable(false);
                j_RRemoveButton.setEnabled(true);
                jUpdateButton.setEnabled(true);
                j_RUpdateButton.setEnabled(true);
                jTypeSelectorBox.removeAllItems();
                if (currentType == 'c')
                    jTypeSelectorBox.addItem(currentClass.getId());
                else
                    jTypeSelectorBox.addItem(""+currentRoom.getId());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTypeSelectorBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        j_RCancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        j_RRemoveButton = new javax.swing.JButton();
        j_RAddButton = new javax.swing.JButton();
        j_RUpdateButton = new javax.swing.JButton();
        j_RNoField = new javax.swing.JTextField();
        j_RCapField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jClassNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jClassIdField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRoomBox = new javax.swing.JComboBox<>();
        jCancelButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 5)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));
        jPanel3.setMinimumSize(new java.awt.Dimension(113, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(113, 30));

        jTypeSelectorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class", "Room" }));
        jTypeSelectorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeSelectorBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTypeSelectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTypeSelectorBox)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 113, 40);

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(110, 0, 440, 40);

        jSplitPane1.setDividerLocation(1000);

        jPanel6.setBackground(new java.awt.Color(51, 255, 255));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Maximum Capacity :");

        j_RCancelButton.setText("Cancel");
        j_RCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_RCancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Room No.           :");

        j_RRemoveButton.setText("Remove");
        j_RRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_RRemoveButtonActionPerformed(evt);
            }
        });

        j_RAddButton.setText("Add");
        j_RAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_RAddButtonActionPerformed(evt);
            }
        });

        j_RUpdateButton.setText("Update");
        j_RUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_RUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(j_RCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j_RRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j_RAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j_RUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_RNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_RCapField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_RNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_RCapField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j_RUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(j_RCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(j_RRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_RAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Class           :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Room No.  :");

        jClassIdField.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Class  ID     :");

        jRoomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("Remove");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRoomBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jClassIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jClassNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jClassNameField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClassIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jRoomBox))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel7);

        jPanel2.add(jSplitPane1);
        jSplitPane1.setBounds(10, 40, 530, 270);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 550, 316));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTypeSelectorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeSelectorBoxActionPerformed
    changeType();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTypeSelectorBoxActionPerformed

    private void j_RCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_RCancelButtonActionPerformed
    closeForm();        // TODO add your handling code here:
    }//GEN-LAST:event_j_RCancelButtonActionPerformed

    private void j_RAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_RAddButtonActionPerformed
    try
    {    
        int roomId = Integer.valueOf(j_RNoField.getText());
        int roomCapacity = Integer.valueOf(j_RCapField.getText());
        int status = RoomManager.createRoom(new Room(roomId, roomCapacity));
        if (status > 0){
         JOptionPane.showMessageDialog(this, "Room Created");
         closeForm();
        }
        else
            JOptionPane.showMessageDialog(this, "Operation Failed");
    }  
    catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(this, "INVALID INPUT");
        Logger.getLogger(ClassandRoomManager.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_j_RAddButtonActionPerformed

    private void j_RUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_RUpdateButtonActionPerformed
    try
    {    
        int roomId = Integer.valueOf(j_RNoField.getText());
        int roomCapacity = Integer.valueOf(j_RCapField.getText());
        int status = RoomManager.updateRoom(currentRoom.getId(),
                new Room(roomId, roomCapacity));
        if (status > 0){
         JOptionPane.showMessageDialog(this, "Room Updated");
         closeForm();
        }
        else
            JOptionPane.showMessageDialog(this, "Operation Failed");
    }  
    catch(NumberFormatException ex){
       JOptionPane.showMessageDialog(this, "INVALID INPUT");
        Logger.getLogger(ClassandRoomManager.class.getName()).log(Level.SEVERE, null, ex);
    }    
    }//GEN-LAST:event_j_RUpdateButtonActionPerformed

    private void j_RRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_RRemoveButtonActionPerformed
    
        int status = RoomManager.deleteRoom(currentRoom);
        System.out.println(status);
        if (status > 0){
         JOptionPane.showMessageDialog(this, "Room Deleted");
         closeForm();
        }      
        else
            JOptionPane.showMessageDialog(this, "Nothing was removed");
    }//GEN-LAST:event_j_RRemoveButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        closeForm();        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        
        int status = I_ClassControl.deleteClass(currentClass);
        if (status > 0){
         JOptionPane.showMessageDialog(this, "Class Removed");
         closeForm();
        }
        else
            JOptionPane.showMessageDialog(this, "Nothing was removed");
    }//GEN-LAST:event_jRemoveButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
            String id = jClassIdField.getText();
        String className = jClassNameField.getText();
        if (className == null || className.isBlank() || className.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Invalid Class Name");
            return;
        }
        int roomId = jRoomBox.getSelectedIndex() > 0 ?
        Integer.valueOf(""+jRoomBox.getSelectedItem()) : -1;
        if (roomId == -1)
        {
            JOptionPane.showMessageDialog(this, "Invalid Room Selection");
            return;
        }
        int status = I_ClassControl.createClass(new I_Class(id, className, roomId));
        if (status > 0){
         JOptionPane.showMessageDialog(this, "Class Created");
         closeForm();
        }
        else
            JOptionPane.showMessageDialog(this, "Operation Failed");
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        String id = jClassIdField.getText();
        String className = jClassNameField.getText();
        if (className == null || className.isBlank() || className.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Invalid Class Name");
            return;
        }
        int roomId = jRoomBox.getSelectedIndex() > 0 ?
        Integer.valueOf(""+jRoomBox.getSelectedItem()) : -1;
        if (roomId == -1)
        {
            JOptionPane.showMessageDialog(this, "Invalid Room Selection");
            return;
        }
        int status = I_ClassControl.updateClass(currentClass.getId(),
                new I_Class(id, className, roomId));
        if (status > 0){
         JOptionPane.showMessageDialog(this, "Class Updated");
         closeForm();
        }
        else
            JOptionPane.showMessageDialog(this, "Operation Failed");
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    void closeForm()
    {
         if (parentClass != null)
        {
            parentClass.setVisible(true);
            parentClass = null;
        }
        this.dispose();
    }
    private void changeType()
    {
       if (mode == 'e')
           return;
    currentType  =jTypeSelectorBox.getSelectedIndex() == 0 ?
         'c' : 'r';
    applyType();
    
    }
    private void applyType(){
        if (currentType == 'c')
        {
            jLabel1.setText("Class");
    jSplitPane1.setDividerLocation(1000);
    ArrayList<Room> rooms = RoomManager.getAvailableRooms();
    jRoomBox.removeAllItems();
    jClassIdField.setText(I_ClassControl.getAvailableID());
    jRoomBox.addItem("Select Room");
    rooms.forEach(room -> {
        jRoomBox.addItem(""+room.getId());
        });
    if (mode == 'c')
        jRoomBox.setSelectedIndex(0);
    else{
        jClassIdField.setText(currentClass.getId());
        jClassNameField.setText(currentClass.getName());
        jRoomBox.addItem(""+currentClass.getRoomId());
        jRoomBox.setSelectedItem(""+currentClass.getRoomId());
    }
        }
        else
        {        
    jSplitPane1.setDividerLocation(0);
    if (mode == 'e')
    {
        j_RNoField.setText(""+currentRoom.getId());
        j_RCapField.setText(""+currentRoom.getSittingCapacity());
    }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassandRoomManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassandRoomManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassandRoomManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassandRoomManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {       
                new ClassandRoomManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JTextField jClassIdField;
    private javax.swing.JTextField jClassNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JComboBox<String> jRoomBox;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox<String> jTypeSelectorBox;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JButton j_RAddButton;
    private javax.swing.JButton j_RCancelButton;
    private javax.swing.JTextField j_RCapField;
    private javax.swing.JTextField j_RNoField;
    private javax.swing.JButton j_RRemoveButton;
    private javax.swing.JButton j_RUpdateButton;
    // End of variables declaration//GEN-END:variables
}
